Fix translate
Abhinav1997/NekoCollector pull request #10
Opened 2016-11-05 18:35 UTC by Blagish

Fix possible misunderstanding in the 'Treat' word translation,

2016-11-05 21:56 UTC, sergeysova requested changes
@Abhinav1997 please close this
#11

2016-11-05 21:56 UTC, LestaD commented on app/src/main/res/values-ru/arrays.xml
> +    <item>Вкусняшка</item>
@Blagish Простонаречие здесь будет избыточно

2016-11-06 15:28 UTC, Blagish commented on app/src/main/res/values-ru/arrays.xml
> +    <item>Вкусняшка</item>
Возможно. Но сладость там одна, а не много. Просто же "Сладость" звучит как-то размыто и неопределённо.

2016-11-06 16:39 UTC, LestaD commented on app/src/main/res/values-ru/arrays.xml
> +    <item>Вкусняшка</item>
@Blagish Для кота всё вышеперечисленное является вкусняшкой, более или менее. В данном случае необходимо уточнить, что будет именно сладость, хоть в пример приведен только пончик.
В дальнейшем планируется добавить другие виды еды, так что лучше уточнить сразу

2016-11-11 23:39 UTC, LestaD commented
@Abhinav1997 now you can close that PR without merge

2016-11-12 19:35 UTC, closed without merging