Fix russian translation
Abhinav1997/NekoCollector pull request #11
Opened 2016-11-05 18:35 UTC by Blagish

Fixed some mistakes and sentences's sense.

2016-11-05 21:54 UTC, sergeysova requested changes
Очень рекомендую выучить правила построения предложений на русском языке, прежде чем предлагать такие изменения.

@Abhinav1997, I propose to close this pull request, because author don't knows rules of russian language

2016-11-05 21:54 UTC, LestaD commented on app/src/main/res/values-ru/strings.xml
> +    <string name="instructions_text">Игра очень проста. Чтобы выбрать корм, нажмите на пустую миску. Теперь ждите, когда кот почувствует запах и прибежит. Собирите столько уникальных котов, сколько с
"соб**е**рите"

2016-11-05 21:54 UTC, LestaD commented on app/src/main/res/values-ru/strings.xml
> +    <string name="about">О игре</string>
"О**б** игре"

2016-11-05 21:54 UTC, LestaD commented on app/src/main/res/values-ru/strings.xml
> +    <string name="close_app">Теперь вы можете закрыть приложение. Чуть позже придёт кот.</string>
В данном случае твой вариант является констатацией факта со сложной постановкой слов в предложении. В оригинале текст является подсказкой подсказывающий пользователю.

2016-11-05 21:54 UTC, LestaD commented on app/src/main/res/values-ru/strings.xml
> +    <string name="cat_dialog_return_message">Похоже, вернулся уже Ваш кот. Пробуйте разные виды корма, чтобы приманить новых котов.</string>
Твоя форма говорит о том, что "кот наконец вернулся". Но в оригинале уточняется, что "это вернулся именно Ваш кот, а не новый". Да и твоя форма это просторечие.

2016-11-06 15:26 UTC, Blagish commented on app/src/main/res/values-ru/strings.xml
> +    <string name="cat_dialog_return_message">Похоже, вернулся уже Ваш кот. Пробуйте разные виды корма, чтобы приманить новых котов.</string>
Подразумевается не "вернулся уже", а "уже Ваш".

2016-11-06 15:26 UTC, Blagish commented on app/src/main/res/values-ru/strings.xml
> +    <string name="close_app">Теперь вы можете закрыть приложение. Чуть позже придёт кот.</string>
Хорошо, я неправ.

2016-11-06 15:26 UTC, Blagish commented on app/src/main/res/values-ru/strings.xml
> +    <string name="instructions_text">Игра очень проста. Чтобы выбрать корм, нажмите на пустую миску. Теперь ждите, когда кот почувствует запах и прибежит. Собирите столько уникальных котов, сколько с
Черт, не заметил.

2016-11-06 15:27 UTC, Blagish commented on app/src/main/res/values-ru/strings.xml
> +    <string name="about">О игре</string>
Это да, мой косяк.

2016-11-06 15:36 UTC, Blagish commented
Благодарю за нахождение моих ошибок, @LestaD. Скорее всего, этот реквест не пройдет и будет закрыт, но я хотя бы буду более внимателен к своей орфографии.

Правила так-то я знаю, но, видимо, проявил некомпетентность по отношению к проверке своей писанины. Впредь обещаю таким не быть, хотя какая кому разница?

2016-11-06 15:43 UTC, Blagish commented
Oh, by the way. @Abhinav1997, please, do not close this until me with @LestaD will come to an agreement.

2016-11-06 16:37 UTC, LestaD commented on app/src/main/res/values-ru/strings.xml
> +    <string name="cat_dialog_return_message">Похоже, вернулся уже Ваш кот. Пробуйте разные виды корма, чтобы приманить новых котов.</string>
@Blagish всё таки здесь имеется ввиду, что вернулся именно Ваш кот, а не новый. Потому что есть всего два варианта (утрирую):
- Ура, пришел новый кот
- Вернулся Ваш кот

2016-11-07 15:07 UTC, LestaD commented
@Abhinav1997  now you can close that PR

2016-11-12 19:35 UTC, closed without merging